### ISSUE TITLE
Game page link is broken : 404  There isn't a GitHub Pages site here.

### ISSUE THREAD

**Issue by satourne** [kana/othello-js#1]
Hi,

Great code, isn't it ?

There is a broken link in your instructions/documentation in that page : https://github.com/kana/othello-js and also in the README.md file.
[Try it online](http://kana.github.com/othello-js/). is broken, a good address is https://kana.github.io/othello-js/
I haven't looked for any other errors like this in others files...

HAGD.

**Comment by satourne** [comment]
Oh,
THANKS !

**Comment by kana** [comment]
Thank you for the report. I've fixed the broken link.
