### ISSUE TITLE
MCTS：相手側視点での子ノード選択の基準について

### ISSUE THREAD

**Issue by bakanaouji** [kana/othello-js#13]
モンテカルロ木探索の子ノード選択についてです．

モンテカルロ木探索において，自分→相手→自分→相手・・・，とプレイヤーが切り替わりながら子ノードを選択していますが，常に「自分」の利得を最大にする行動を選択しているように思われます．

相手側視点で子ノードを選択するときは，`(n.visits - n.wins) / n.visits + Math.sqrt(2 * Math.log(totalVisits) / n.visits)`を最大とする行動を選択するのではないでしょうか？

https://github.com/kana/othello-js/blob/7cb20efa72c629d0409bb62a60ef5848293ab7cc/othello.js#L804-L811

**Comment by kana** [comment]
うーん、言われてみると確かにその通りですね。実際にその変更を入れたものと元々のもので対戦させてみたところ、70勝30敗くらいの力量差になりました。
という訳で修正しました: https://github.com/kana/othello-js/commit/f86d063c338dc62450fd1fec6f2e08c77870ba72#diff-2ea98bb66b48750277dcf1628ccd655aR810 修正前のバージョン(Type M-1024/old)も残してあるので実際にどれくらい差があるか試せるようにしてます。
ご指摘ありがとうございました。
